spring:
  datasource:
    url: jdbc:mysql://localhost:3306/no_way_home?autoReconnect=true
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true